version: "2"
engines:
  reek: 
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-64
    checks:
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/StringLiterals:
        enabled: false
