AllCops:
  Include:
  - "app/**/*.rb"
  - "lib/**/*.rb"
  - "lib/**/*.rake"
  Exclude:
  - "config/**/*.rb"
  - "vendor/**/*"
  - "db/**/*"
  - "bin/**/*"
  DisplayCopNames: true

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Max: 125
Metrics/MethodLength:
  Max: 25
